//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\tools\TinyLanguage\TinyLanguage.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TinyLanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ITinyLanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] TinyLanguageParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] TinyLanguageParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlock([NotNull] TinyLanguageParser.CodeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlock([NotNull] TinyLanguageParser.CodeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] TinyLanguageParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] TinyLanguageParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] TinyLanguageParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] TinyLanguageParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.if_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stat([NotNull] TinyLanguageParser.If_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.if_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stat([NotNull] TinyLanguageParser.If_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.condition_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition_block([NotNull] TinyLanguageParser.Condition_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.condition_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition_block([NotNull] TinyLanguageParser.Condition_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_block([NotNull] TinyLanguageParser.Stat_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_block([NotNull] TinyLanguageParser.Stat_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLanguageParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] TinyLanguageParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLanguageParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] TinyLanguageParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atomExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomExpr([NotNull] TinyLanguageParser.AtomExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atomExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomExpr([NotNull] TinyLanguageParser.AtomExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] TinyLanguageParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] TinyLanguageParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>additiveExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] TinyLanguageParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>additiveExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] TinyLanguageParser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>equalityExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] TinyLanguageParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>equalityExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] TinyLanguageParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] TinyLanguageParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] TinyLanguageParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParExpr([NotNull] TinyLanguageParser.ParExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parExpr</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParExpr([NotNull] TinyLanguageParser.ParExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numberAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberAtom([NotNull] TinyLanguageParser.NumberAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numberAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberAtom([NotNull] TinyLanguageParser.NumberAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>idAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdAtom([NotNull] TinyLanguageParser.IdAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>idAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdAtom([NotNull] TinyLanguageParser.IdAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stringAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringAtom([NotNull] TinyLanguageParser.StringAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringAtom</c>
	/// labeled alternative in <see cref="TinyLanguageParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringAtom([NotNull] TinyLanguageParser.StringAtomContext context);
}
